In [7]:
# Numpy works mainly with arrays and matrix
import numpy as np

## Create Array

In [95]:
#convert a list into array
y = np.array([1,0,0]) 
print(y)
y= np.array([y,y+2])
print(y)
#multi-dimension array
y = np.array([[1,0,0],[0,1,0]])
print(y)

[1 0 0]
[[1 0 0]
 [3 2 2]]
[[1 0 0]
 [0 1 0]]


In [122]:
n= np.arange(0,30,2)  #(start, stop, interval)
print(n)
n = np.arange(10)
print(n)
n= np.linspace(0,9,10) #(start, stop, the numbers of values)
print(n)

n=np.random.randint(0,10,(2,3)) #(start, stop, dimensions) 
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[8 1 2]
 [1 7 7]]


In [22]:
x=np.ones((3,2))
print(x)
x=np.zeros((2,3))
print(x)

#define vectors
x=np.eye(3)
print(x)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [109]:
#index:
print(n)
print(n[0], n[-1], n[0:3])
print(n[5::2]) # from 6 digit to end, interval by 2
print(n[n<5])

print(y)
print(y[1,1:])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
0.0 9.0 [ 0.  1.  2.]
[ 5.  7.  9.]
[ 0.  1.  2.  3.  4.]
[[1 0 0]
 [0 1 0]]
[1 0]


# change array

In [76]:
#change data type
print(x.dtype)
x= x.astype('f')
print(x.dtype)

int32
float32


In [73]:
n= np.linspace(0,9,10)
print(n)

#reshape an array into multi-dimension
n= n.reshape(2,5)
print(n)

#check dimesion
print(n.shape) 

#swap rows and columns
print(n.T) 

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
(2, 5)
[[ 0.  5.]
 [ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]]


In [25]:
print(n)
x=np.diag(n)
print(x)
# diag only show values in place

[[ 0.   0.5  1. ]
 [ 1.5  2.   2.5]
 [ 3.   3.5  4. ]]
[ 0.  2.  4.]


In [31]:
x=np.array([1,2,3]*3)
print(x)
x=np.repeat([1,2,3],3)
print(x)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [120]:
r = np.arange(36)
r= r.reshape(6,6)
print(r)
r1= r[:3,:3]
print(r1)
#change all values in r1 into 0
r1[:] = 0
print(r1)
# values in r also changed
print(r)

r2= r1.copy()
r2[:]= 10
print(r2)
print(r)
#when use copy() function, r is not changed

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


# array calculation

In [46]:
x= np.ones((2,3))
print(x)
y= x*2
print(y)

print(x+y)
print(y**2)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 3.  3.  3.]
 [ 3.  3.  3.]]
[[ 4.  4.  4.]
 [ 4.  4.  4.]]


In [91]:
# dot product:
a=np.array([3,1,0])
b=np.array([2,1,1])
x1= a.dot(b)
x2= np.dot(a,b)
print(x1, x2) #same functions

7 7


dot product is the sum of all similar position products


![alt text](afsdfsgsggsg.PNG )



In [92]:
print(a)

#where is the max value?
print(a.max())       #value
print(a.argmax())    #location
print(a.min())
print(a.argmin()) 

print(a.mean())
print(a.std())
print(a.sum())

[3 1 0]
3
0
0
2
1.33333333333
1.24721912892
4


# iterating over array

In [131]:
print(n)

for row in n:
    print(row)
    
print(range(len(n)))
for i in range(len(n)):
    print(n[i])

[[8 1 2]
 [1 7 7]]
[8 1 2]
[1 7 7]
range(0, 2)
[8 1 2]
[1 7 7]


In [133]:
m= n*2
print(m)

for x,y in zip(m,n):
    print(x,'+',y,'=',x+y)

[[16  2  4]
 [ 2 14 14]]
[16  2  4] + [8 1 2] = [24  3  6]
[ 2 14 14] + [1 7 7] = [ 3 21 21]


## Distribution

In [8]:
print('binomial is a binary distribution: yes or no')
np.random.binomial(1000,0.5)/1000
# (run 1000 times, 50% to get 0)

binomial is a binary distribution: yes or no


0.495

In [9]:
#normal distribution
distribution = np.random.normal(0.75, size =100)
# 0.75 is expected value( mean)
distribution

array([ 0.76987688,  0.60176259,  1.96310856,  0.56575838,  2.07892495,
       -0.54137669, -0.73252542,  1.3070077 , -0.49991286,  0.57713134,
       -0.0103932 , -0.06559995,  2.81853988,  1.2092406 ,  1.4074223 ,
        1.53915096,  1.83187395, -1.06110105,  0.61551884,  1.23629784,
        0.93252736, -3.09807233,  0.2178406 ,  1.40251557,  1.9330069 ,
       -0.31293782,  1.06009479, -0.15942074,  1.75426676,  0.69295557,
        2.11787656,  0.67450954, -0.3175819 ,  1.76194063,  2.49894363,
        0.26641149,  1.69597163, -0.7727651 , -0.00919138, -0.39466583,
        0.61481423, -0.1220259 , -0.71791205,  0.21469855,  0.85325159,
        1.02624759,  0.97376432,  0.03808031, -1.54524461,  1.17576007,
       -0.1498987 ,  0.79370211,  0.58925254, -0.87348008,  0.98534251,
        0.12839641, -0.32313764,  0.57046093,  0.42626844,  0.10235678,
        0.68688458,  1.08311692,  0.04309   ,  1.21667794, -0.03865815,
       -0.04306096, -0.62298893,  1.36122854, -0.02853953,  0.76

In [6]:
np.std(distribution)

1.0062925229652679

## A/B Testing: Hypothesis test

In [10]:
distribution2 = np.random.normal(0.74, size =100)

In [11]:
print("Alternative hypothsis: distribution has similar expected value as distribution2")
print("Null hypothsis: distribution has different expected value as distribution2")
print('Confidence level: 0.05')

Alternative hypothsis: distribution has similar expected value as distribution2
Null hypothsis: distribution has different expected value as distribution2
Confidence level: 0.05


In [12]:
from scipy import stats

stats.ttest_ind(distribution,distribution2)

Ttest_indResult(statistic=-0.72467273054923931, pvalue=0.46950830167945401)

In [13]:
print("P-value is large than 0.05, can't reject null hypothesis")
print("Conclusion:distribution has a different mean as distribution 2")

P-value is large than 0.05, can't reject null hypothesis
Conclusion:distribution has a different mean as distribution 2
