In [1]:
# Numpy works mainly with arrays and matrix
import numpy as np

## Create Array

In [95]:
#convert a list into array
y = np.array([1,0,0]) 
print(y)
y= np.array([y,y+2])
print(y)
#multi-dimension array
y = np.array([[1,0,0],[0,1,0]])
print(y)

[1 0 0]
[[1 0 0]
 [3 2 2]]
[[1 0 0]
 [0 1 0]]


In [122]:
n= np.arange(0,30,2)  #(start, stop, interval)
print(n)
n = np.arange(10)
print(n)
n= np.linspace(0,9,10) #(start, stop, the numbers of values)
print(n)

n=np.random.randint(0,10,(2,3)) #(start, stop, dimensions) 
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[8 1 2]
 [1 7 7]]


In [22]:
x=np.ones((3,2))
print(x)
x=np.zeros((2,3))
print(x)

#define vectors
x=np.eye(3)
print(x)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [109]:
#index:
print(n)
print(n[0], n[-1], n[0:3])
print(n[5::2]) # from 6 digit to end, interval by 2
print(n[n<5])

print(y)
print(y[1,1:])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
0.0 9.0 [ 0.  1.  2.]
[ 5.  7.  9.]
[ 0.  1.  2.  3.  4.]
[[1 0 0]
 [0 1 0]]
[1 0]


# change array

In [76]:
#change data type
print(x.dtype)
x= x.astype('f')
print(x.dtype)

int32
float32


In [73]:
n= np.linspace(0,9,10)
print(n)

#reshape an array into multi-dimension
n= n.reshape(2,5)
print(n)

#check dimesion
print(n.shape) 

#swap rows and columns
print(n.T) 

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
(2, 5)
[[ 0.  5.]
 [ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]]


In [25]:
print(n)
x=np.diag(n)
print(x)
# diag only show values in place

[[ 0.   0.5  1. ]
 [ 1.5  2.   2.5]
 [ 3.   3.5  4. ]]
[ 0.  2.  4.]


In [31]:
x=np.array([1,2,3]*3)
print(x)
x=np.repeat([1,2,3],3)
print(x)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [120]:
r = np.arange(36)
r= r.reshape(6,6)
print(r)
r1= r[:3,:3]
print(r1)
#change all values in r1 into 0
r1[:] = 0
print(r1)
# values in r also changed
print(r)

r2= r1.copy()
r2[:]= 10
print(r2)
print(r)
#when use copy() function, r is not changed

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


# array calculation

In [46]:
x= np.ones((2,3))
print(x)
y= x*2
print(y)

print(x+y)
print(y**2)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 3.  3.  3.]
 [ 3.  3.  3.]]
[[ 4.  4.  4.]
 [ 4.  4.  4.]]


In [91]:
# dot product:
a=np.array([3,1,0])
b=np.array([2,1,1])
x1= a.dot(b)
x2= np.dot(a,b)
print(x1, x2) #same functions

7 7


dot product is the sum of all similar position products


![alt text](afsdfsgsggsg.PNG )



In [92]:
print(a)

#where is the max value?
print(a.max())       #value
print(a.argmax())    #location
print(a.min())
print(a.argmin()) 

print(a.mean())
print(a.std())
print(a.sum())

[3 1 0]
3
0
0
2
1.33333333333
1.24721912892
4


# iterating over array

In [131]:
print(n)

for row in n:
    print(row)
    
print(range(len(n)))
for i in range(len(n)):
    print(n[i])

[[8 1 2]
 [1 7 7]]
[8 1 2]
[1 7 7]
range(0, 2)
[8 1 2]
[1 7 7]


In [133]:
m= n*2
print(m)

for x,y in zip(m,n):
    print(x,'+',y,'=',x+y)

[[16  2  4]
 [ 2 14 14]]
[16  2  4] + [8 1 2] = [24  3  6]
[ 2 14 14] + [1 7 7] = [ 3 21 21]
